#pragma config(Sensor, S2,     ,               sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// ROBOPRO || VEATRIZ
#define ROBOPRO


#include "Sortida_1a.h"
#include "Sortida_1b.h"
#include "Sortida_2.h"
#include "Sortida_2b.h"
#include "Sortida_3.h"
#include "Sortida_3v2.h"
#include "Sortida_4_Robopro.h"
#include "Sortida_4_Veatriz.h"
#include "Aliniat_S2.h"
#include "Aliniat_S3.h"

task main()
{
	waitForButtonPress();

	if (getButtonPress(buttonEnter))
	{
		// Tot sense alinear
		Sortida_1b();
		Sortida_2a();
		Sortida_2b();
		Sortida_3();
		Sortida_4_Robopro();
	}
	if (getButtonPress(buttonLeft))
	{
		// Començar en la 2 aliniant-se
		Aliniat_S2();
		Sortida_2a();
		Sortida_2b();
		Sortida_3();
		Sortida_4_Robopro();

	}
	if (getButtonPress(buttonUp))
	{
		// Començar en la 3 aliniant-se
		Aliniat_S3();
		Sortida_3();
		Sortida_4_Robopro();
	}
	if (getButtonPress(buttonRight))
	{
		// des de la sortida 4 alineant-se
		Aliniat_S4();
		Sortida_4_Robopro();
	}
	if (getButtonPress(buttonDown))
	{
		// lliure
	}
}
