#pragma config(Sensor, S2,     ,               sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// ROBOPRO || VEATRIZ
#define ROBOPRO


#include "Sortida_1a.h"
#include "Sortida_1b.h"
#include "Sortida_2.h"
#include "Sortida_2b.h"
#include "Sortida_3.h"
#include "Sortida_3v2.h"
#include "Sortida_4_Robopro.h"
#include "Sortida_4_Veatriz.h"


task main()
{

}
