#pragma config(Sensor, S2,     ,               sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Motors:
//	Rigth: motorB
//	Left: motorC

// Wall:
// 	Vertical: motorD
//	Horizontal: motorA

// Fwd - Forward; Bwd - Backward. Recta direction definitions
// Lft - Left; Rgt - Right. Turns direction definitions

// From max side to middle: 1.2
// From max up to down: 2.65
// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)

// ROBOPRO || VEATRIZ
//#define ROBOPRO
#define VEATRIZ

#include "Core/Core.h"

//#include "Sortida_2bR.h"
//#include "Sortida_2bR_Short.h"
//#include "Sortida_3R.h"
//#include "Sortida_4_Robopro.h"
//
task main()
{
	//Tornem
	MoveMotor(motorD, 2, 30);//2
	Recta(Bwd, 1, 50, true, false);
	WaitForLine(Bwd, 10, 20, Rgt);   // Detectem banc
	Recta(Fwd, 0.5, 50);
	Turn(-92,40,Rgt);
	Recta(Fwd, 0.25, 50, true, false);
	WaitForLine(Fwd, 10, 20, Lft);   // Detectem banc
	Recta(Fwd, 0.4, 20);
	//while(getColorReflected(S3)<=70){
	//	setMotorSpeed(motorC, -40);
	//	setMotorSpeed(motorB, 40);
	//}

//	while(getColorReflected(S3)>=25){
//		setMotorSpeed(motorC, -40);
//		setMotorSpeed(motorB, 30);
//	}
//	setMotorSpeed(motorC, 0);
//	setMotorSpeed(motorB, 0);
//	//delay(5000);
//	//while(getColorReflected(S3)<=50){
//	//	setMotorSpeed(motorC, 20);
//	//	setMotorSpeed(motorB, -20);
//	//}
//	setMotorSpeed(motorC, 0);
//	setMotorSpeed(motorB, 0);
//	delay(5000);

//	FollowLine(0.7, 45, Rgt, Lft, false, false);  // primer tram
//	setMotorSpeed(motorC, 0);
//	setMotorSpeed(motorB, 0);

//	//MoveMotor(motorA, 1, 50);
//	//resetGyro(S2);
//	//delay(300);
//	//Turn(-40, 30, Rgt);
//	//Recta(Fwd, 0.1, 20, false, false);
//	//WaitForBlack(Fwd, 10, 20, Lft);

//	//Recta(Fwd, 0.3, 20, false, false);

//	//while(getColorReflected(S4)>=50){
//	//	setMotorSpeed(motorC, 40);
//	//	setMotorSpeed(motorB, -40);
//	//}

//	//setMotorSpeed(motorC, 0);
//	//setMotorSpeed(motorB, 0);
//	////WaitForLine(Fwd, 10, 20, Lft);   // Detectem banc
//	//FollowLine(0, 30, Lft, Rgt, false, false, 60, 1.6, 65, 0.75);  // primer tram
//	//WaitForBlack(Fwd, 10, 20, Rgt);   // Detectem negre
//	Turn(-40, 40, Rgt);
//	Recta(Fwd, 0.2, 30, true, true);
//	while(getColorReflected(S4)<=30){
//		setMotorSpeed(motorC, -40);
//		setMotorSpeed(motorB, 40);
//	}
//		FollowLine(0, 50, Lft, Rgt, false, false);  // primer tram
// Recta(Fwd, 0.2, 30, false, false);
//	////	WaitForLine(Fwd, 10, 20, Lft);   // Detectem banc

//	FollowLine(2, 50, Lft, Rgt, false, false);  // primer tram

//	//WaitForBlack(Fwd, 10, 20, Lft);   // Detectem negre
//	////	WaitForLine(Fwd, 10, 20, Lft);   // Detectem banc
//	//while(getColorReflected(S4)>=15){
//	//	setMotorSpeed(motorC, -40);
//	//}
//	//setMotorSpeed(motorC, 0);
//	//MoveMotor(motorA, 1, 30);//2
//	//FollowLine(3.5, 40, Lft, Rgt, true, true, 50, 1, 50, 0.6);  // primer tram
//	//MoveMotor(motorD, 2, 30);//2
//	//MoveMotor(motorA, 2, -30);//2
//	////MoveMotor(motorD, 2.7, 30);
//	Recta(Fwd, 4, 30, true, true, 0.9);
//	////MoveMotor(motorD, 2.7, -70);

}
