#pragma config(Sensor, S2,     ,               sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Motors:
//	Rigth: motorB
//	Left: motorC

// Wall:
// 	Vertical: motorD
//	Horizontal: motorA

// Fwd - Forward; Bwd - Backward. Recta direction definitions
// Lft - Left; Rgt - Right. Turns direction definitions

// From max side to middle: 1.2
// From max up to down: 2.65
// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)

// ROBOPRO || VEATRIZ
//#define ROBOPRO
#define VEATRIZ

#include "Core/Core.h"

//#include "Sortida_2bR.h"
//#include "Sortida_2bR_Short.h"
//#include "Sortida_3R.h"
//#include "Sortida_4_Robopro.h"
//
task main()
{

	resetGyro(S2);
	delay(100);
	MoveMotorTime(motorD, 2, 70);
	MoveMotorTime(motorA, 4, 30);

	MoveMotor(motorD, 0.67, -50);
	//MoveMotor(motorA, 1.7, 30);



	WaitForLine(Bwd, 10, 30, Lft);
	Recta(Fwd, 0.1, 50, false, false);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);// Detectem banc
	//Recta(Fwd, 0.1, 50);

	//Ens encarem
	Turn(43, 20, Lft); //43
	//WaitForBlack3(Fwd, 10, 20, Lft, false);// Detectem negre
	//WaitForLine(Fwd, 10, 20, Lft);// Detectem blanc



	Align(Fwd, 2);
	Recta(Fwd, 0.6, 50); //0.6
	MoveMotor(motorD, 2.3, -80);
	MoveMotor(motorA, 2, -60);
	MoveMotorTime(motorA, 0.3, -80);

	MoveMotor(motorD, 2.3, 80);
	Recta(Fwd, 0.8, 50, false, false);
	Recta(Fwd, 0.3, 20, false, false);
	resetGyro(S2);
	delay(100);
	Recta(Bwd, 0.15, 50, false, false);
	MoveMotorAsync(motorA, 1.7, 70); //1.2
	Turn(90, 20, Lft);
	Recta(Bwd, 0.45, 20, false, false);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);

	//Fem la part final
	MoveMotor(motorD, 3, -80);
	Recta(Fwd, 0.45, 30, true, false);
	WaitForBlack(Fwd, 10, 20, Rgt);
	delay(150);
	//MoveMotor(motorD, 0.8, 70);
	flushButtonMessages();
	waitForButtonPress();
}
