#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// F - Forward; B - Backward. Recta direction definitions
// L - Left; R - Right. Turns direction definitions

// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)


#include "Core/Core.h"

task main()
{
	////setMotorSync(motorB, motorC, 0, 0);
	//setMotorBrakeMode(motorB, motorCoast);
	//setMotorBrakeMode(motorC, motorCoast);

	//delay(50);

	////setMotorSync(motorB, motorC, 1, 3);
	//float c_speed = 5;
	//float dt = 0.01;
	//while (c_speed < 10)
	//{
	//	float err = (getMotorEncoder(motorC) - getMotorEncoder(motorB)) / 360.0;
	//	float turn = GetCorrection(err * 10000, 20, 5);

	//	datalogAddValue(0, (int)(err * 10000));
	//	datalogAddValue(1, (int)(turn * 10));
	//	datalogAddValue(2, (int)(c_speed));

	//	setMotorSync(motorB, motorC, turn, c_speed);

	//	c_speed += 10 * dt;

	//	delay(dt * 1000);
	//}

	//delay(5000);
	Recta(F, 5, 70);
	//FollowLine(R, 2, 20);
}
