#pragma config(Sensor, S2,     ,               sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Motors:
//	Rigth: motorB
//	Left: motorC

// Wall:
// 	Vertical: motorD
//	Horizontal: motorA

// Fwd - Forward; Bwd - Backward. Recta direction definitions
// Lft - Left; Rgt - Right. Turns direction definitions

// From max side to middle: 1.2
// From max up to down: 2.65
// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)

// ROBOPRO || VEATRIZ
//#define ROBOPRO
#define VEATRIZ

#include "Core/Core.h"
#include "STren_Mal.h"
#include "SDron_Mal.h"
#include "SCheta_Mal.h"
#include "SBlocs_Mal.h"

//#include "Sortida_2bR.h"
//#include "Sortida_2bR_Short.h"
//#include "Sortida_3R.h"
//#include "Sortida_4_Robopro.h"
//
task main()
{
	waitForButtonPress();
	if (getButtonPress(buttonEnter))
	{
		flushButtonMessages();
		waitForButtonPress();
		if (getButtonPress(buttonLeft))
		{
			Sortida_1();
			Sortida_2();
			Sortida_3();
			Sortida_4();
		}
		if (getButtonPress(buttonRight))
		{
			flushButtonMessages();
			Align_S1();
			Sortida_1();
			Sortida_2();
			Sortida_3();
			Sortida_4();
		}

	}
	if (getButtonPress(buttonUp))
	{
		flushButtonMessages();
		waitForButtonPress();
		if (getButtonPress(buttonLeft))
		{
			Sortida_2();
			Sortida_3();
			Sortida_4();
		}
		if (getButtonPress(buttonRight))
		{
			Align_S2();
			Sortida_2();
			Sortida_3();
			Sortida_4();
		}
	}
	if (getButtonPress(buttonRight))
	{
		flushButtonMessages();
		waitForButtonPress();
		if (getButtonPress(buttonLeft))
		{
			Sortida_3();
			Sortida_4();
		}
		if (getButtonPress(buttonRight))
		{
			Align_S3();
			Sortida_3();
			Sortida_4();
		}
	}
	if (getButtonPress(buttonDown))
	{
		flushButtonMessages();
		waitForButtonPress();
		if (getButtonPress(buttonLeft))
		{
			Sortida_4();
		}
		if (getButtonPress(buttonRight))
		{
			Align_S4();
			Sortida_4();
		}
	}
}
