#pragma config(Sensor, S2,     ,               sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Motors:
//	Rigth: motorB
//	Left: motorC

// Wall:
// 	Vertical: motorD
//	Horizontal: motorA

// Fwd - Forward; Bwd - Backward. Recta direction definitions
// Lft - Left; Rgt - Right. Turns direction definitions

// From max side to middle: 1.2
// From max up to down: 2.65
// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)

// ROBOPRO || VEATRIZ
#define ROBOPRO
//#define VEATRIZ

#include "Core/Core.h"

//#include "Sortida_2bR.h"
//#include "Sortida_2bR_Short.h"
//#include "Sortida_3R.h"
//#include "Sortida_4_Robopro.h"

task main()
{
	//Align wall(no acabat)
	MoveMotorTime(motorA, 4, -20);
	MoveMotorTime(motorD, 5, 30);
	MoveMotor(motorD, 1, -50);
	MoveMotor(motorA, 0.8, 50);  //abans 0.8
	//avançar fins línia(no fet)
	//avançar fins prova
	waitForButtonPress();
	FollowLine(2, 40, Rgt, Lft, true, false);  // primer tram
	FollowLine(0.5, 30, Rgt, Lft, false, false, 20); // corba
	FollowLine(2.2, 40, Rgt, Lft, false, true);  // segon tram
	WaitForLine(Fwd, 10, 20, Lft);   // Detectem banc
	Recta(Fwd, 0.6, 10); //???
	MoveMotor(motorD, 1, -60);
	MoveMotor(motorA, 0.4, -50);
	Recta(Fwd, 0.5, 40);  // posiciones cercle empenyent grua
	MoveMotor(motorD, 1.1, -50);
	MoveMotor(motorA, 0.4, -50);  // deixem millora i contenidor
	MoveMotor(motorD, 0.5, 50);
	Recta(Fwd, 0.4, 30);
	//MoveMotor(motorA, 0.6, 50);
	//MoveMotor(motorD, 1.8, -50);
	//MoveMotor(motorA, 1, -50);


	//Fer missió avió
	//MoveMotor(motorA, 0.7, -30);
	//MoveMotor(motorD, 1.6, -50);
	//MoveMotor(motorD, 2, 50);
	////marxar
	//MoveMotor(motorA, 1, 30);
	//Recta(Fwd, 0.5, 30);
	////Turn(320, 30);
	//while(getColorReflected(S3)>= 20){
	//	setMotorSpeed(MotorB, 30);
	//}
	//	setMotorSpeed(MotorB, 0);
	//MoveMotor(motorA, 1, -30);
	//MoveMotor(motorD, 1.8, -50);
	//FollowLine(3, 40, Rgt, Lft);
}
