#pragma config(Sensor, S2,     ,               sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Motors:
//	Rigth: motorB
//	Left: motorC

// Wall:
// 	Vertical: motorD
//	Horizontal: motorA

// Fwd - Forward; Bwd - Backward. Recta direction definitions
// Lft - Left; Rgt - Right. Turns direction definitions

// From max side to middle: 1.2
// From max up to down: 2.65
// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)

// ROBOPRO || VEATRIZ
//#define ROBOPRO
#define VEATRIZ

#include "Core/Core.h"

//#include "Sortida_2bR.h"
//#include "Sortida_2bR_Short.h"
//#include "Sortida_3R.h"
//#include "Sortida_4_Robopro.h"

task main()
{
	//Align wall(no acabat)
	MoveMotorTime(motorA, 4, -20);
	MoveMotorTime(motorD, 5, 30);
	MoveMotor(motorA, 1.5, 50);  //abans 0.8
	MoveMotor(motorD, 1.3, -50);

	////avançar fins línia(no fet)
	////avançar fins prova
	waitForButtonPress();
	FollowLine(2, 40, Rgt, Lft, true, false, 60, 0.9, 60, 0.1);  // primer tram
	FollowLine(0.3, 30, Rgt, Lft, false, false, 60, 1.3, 60, 0.5);  //corba BDP 20
	FollowLine(2.3, 50, Rgt, Lft, false, false, 60, 0.9, 60, 0.1);  // segon tram

	MoveMotorAsync(motorD, 0.3, 50);
	WaitForLine(Fwd, 10, 20, Lft);   // Detectem banc
	resetGyro(S2);
	Recta(Fwd, 0.5, 30, false, true); //Avançar per tirar pont

	//tirar pont deixar peça i moure grua
	MoveMotor(motorD, 1.5, -60);//1
	MoveMotor(motorA, 0.3, -50);

	//acabem cursa grua
	Recta(Fwd, 0.6, 40, true, false); //0.4
	Turn(0, 50, Rgt);
	MoveMotor(motorA, 1.1, -50);

	MoveMotorAsync(motorA, 1.4, 70);
	MoveMotor(motorD, 2.9, 60);

	Recta(Fwd, 0.55, 30);
	while(getColorReflected(S4)>=20){
	setMotorSpeed(motorB, -20);
	setMotorSpeed(motorC, 15);
	}

	FollowLine(1.7, 40, Lft, Rgt, false, false, 35, 0.9, 60, 0.1);
	WaitForLine(Fwd, 10, 20, Rgt);
	Turn(-88, 30, Rgt);

	Recta(Bwd, 2.5, 70, false, false);//1
	resetGyro(S2);

	MoveMotor(motorD, 2.5, -60);
	MoveMotor(motorA, 1.4, -60);//1.5
	MoveMotorAsync(motorA, 1.1, 60);
	MoveMotor(motorD, 2, 60);


	resetMotorEncoder(motorC);
	Recta(Fwd, 0.7, 40, false, true);
	delay(10000);
	WaitForLine(Fwd, 10, 30, Rgt);
	float count;
	float count1;
	float motormov;
	count = getMotorEncoder(motorC);
	count1 = count  + 360;
	count1 = count1/-10;
	motormov = count1 * 0.13;
	MoveMotor(motorA, -motormov, 30);//MoveMotor(30)
	count = getMotorEncoder(motorC)/360;
	float mov;
	delay(5000);
	mov = 1.72+count;
	Recta(Fwd, mov, 40, false, true);
	MoveMotor(motorD, 2.5, -60);
	Recta(Fwd, 1.2, 50,true, false);
	Recta(Fwd, 1, 30, false, true);
	MoveMotor(motorD, 1, 50);
	Recta(Bwd, 1, 30);
	MoveMotor(motorD, 1, -30);
	Recta(Fwd, 0.7, 30);

//Tornem
	MoveMotorAsync(motorD, 1.5, 70);//2
	Recta(Bwd, 1.5, 50);
	Turn(-90,40,Rgt);
	WaitForBlack(Fwd, 10, 40, Lft);   // Detectem negre
	MoveMotorAsync(motorD, 0.2, 70);
	Recta(Fwd, 0.3, 20, false, false);

		while(getColorReflected(S4)<=85){
		setMotorSpeed(motorC, 30);
		setMotorSpeed(motorB, -30);
		}

		while(getColorReflected(S4)>=45){
		setMotorSpeed(motorC, 30);
		setMotorSpeed(motorB, -40);
		}

		while(getColorReflected(S4)<=25){
		setMotorSpeed(motorC, -20);
		setMotorSpeed(motorB, 20);
		}

	MoveMotorAsync(motorD, 0.3, 70);//2
	FollowLine(0.3, 45, Lft, Rgt, false, false, 0, 0.9, 60, 0.1);  // primer tram

		while(getColorReflected(S4)>=55){
		setMotorSpeed(motorC, 20);
		setMotorSpeed(motorB, -20);
		}

	FollowLine(0.3, 60, Lft, Rgt, false, false, 0, 0.9, 60, 0.1);  // primer tram

	WaitForBlack2(Fwd, 10, 30, Rgt, 0.7);   // Detectem negre
	WaitForLine2(Fwd, 10, 20, Lft, 0.7);   // Detectem blanc
	Recta(Fwd, 0.1, 20, false, false, 0.75);

	setMotorSpeed(motorC, 0);
	setMotorSpeed(motorB, 0);

		while(getColorReflected(S4)>=20){
		setMotorSpeed(motorC, -30);
		setMotorSpeed(motorB, 30);
		}
		delay(40);
		setMotorSpeed(motorC, 0);
		setMotorSpeed(motorB, 0);

	FollowLine(1.8, 60, Lft, Rgt, false, false, 35, 0.9, 60, 0.1);
	Recta(Fwd, 2, 75, false, false, 1, 0.85);
	Recta(Fwd, 4, 75, false, false);
}
