#pragma config(Sensor, S2,     ,               sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Motors:
//	Rigth: motorB
//	Left: motorC

// Wall:
// 	Vertical: motorD
//	Horizontal: motorA

// Fwd - Forward; Bwd - Backward. Recta direction definitions
// Lft - Left; Rgt - Right. Turns direction definitions

// From max side to middle: 1.2
// From max up to down: 2.65
// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)

// ROBOPRO || VEATRIZ
#define ROBOPRO
//#define VEATRIZ

#include "Core/Core.h"

//#include "Sortida_2bR.h"
//#include "Sortida_2bR_Short.h"
//#include "Sortida_3R.h"
//#include "Sortida_4_Robopro.h"

task main()
{
	////Align wall(no acabat)
	MoveMotorTime(motorD, 2, 70);
	MoveMotorTime(motorA, 4, -30);
	MoveMotor(motorD, 3, -50);
	MoveMotor(motorA, 1.45, 30);
	waitForButtonPress();

	//Fer tractors
	MoveMotorAsync(motorA, 1.5, -30);
	Recta(Fwd, 1.9, 50);
	FollowLine(1.5, 40, Rgt, Lft);
	Recta(Fwd, 0.4, 50);

	//Agafar Gallina
	//MoveMotor(motorD, 0.8, 50);
	//MoveMotor(motorA, 0.2, 50);
	//delay(5000);
	//Recta(Fwd, 1, 50);
	//delay(5000);
	//FollowLine(1, 40, Rgt, Lft);
	//MoveMotor(motorD, 0.8, -50);
	////Recolocació
	//if(getColorReflected <= 20)
	//	While(getColorReflected
	//MoveMotor(motorA, 1, 30);
	//Recta(Fwd, 0.5, 30);
	////Turn(320, 30);

}
