#pragma config(Sensor, S2,     ,               sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Motors:
//	Rigth: motorB
//	Left: motorC

// Wall:
// 	Vertical: motorD
//	Horizontal: motorA

// Fwd - Forward; Bwd - Backward. Recta direction definitions
// Lft - Left; Rgt - Right. Turns direction definitions

// From max side to middle: 1.2
// From max up to down: 2.65
// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)

// ROBOPRO || VEATRIZ
//#define ROBOPRO
#define VEATRIZ

#include "Core/Core.h"

//#include "Sortida_2bR.h"
//#include "Sortida_2bR_Short.h"
//#include "Sortida_3R.h"
//#include "Sortida_4_Robopro.h"

task main()
{
	//MoveMotorAsync(motorD, 0.7, 30);
	////MoveMotor(motorA, -1, 50);
	////waitForButtonPress();
	////FollowLine(2.5, 40, Rgt, Lft, true, false, 45, 0.9, 60, 0.1);  // primer tram
	////FollowLine(2.5, 50, Rgt, Lft, false, false, 60, 0.9, 60, 0.1);  // segon tram
	//WaitForLine(Fwd, 10, 20, Lft);   // Detectem banc
	//Recta(Fwd, 0.4, 20, false, true); // ens posicionem per deixar helicopter
	////deixem peça
	//MoveMotor(motorA, 1, 40);
	//MoveMotor(motorD, 0.7, -40);
	//MoveMotor(motorD, 0.02, 40);


	//MoveMotor(motorA, 0.8, 40);
	////Cercle blau
	//MoveMotor(motorD, 0.7, 40);
	////MoveMotor(motorA, 0.3, 40);
	////Turn(15, 20, Lft);
	//FollowLine(2.3, 40, Rgt, Lft, true, true, 60,  0.8, 60, 0.1);  // segon tram//2.5
	//MoveMotor(motorA, 1.5, -40);
	MoveMotor(motorD, 3, 40);
	//MoveMotor(motorA, 1.5, 40);
	Recta(Bwd, 0.9, 50);
	Turn(-32, 20, Rgt);
	Recta(Bwd, 2.3, 50);


}
