#pragma config(Sensor, S2,     ,               sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Motors:
//	Rigth: motorB
//	Left: motorC

// Wall:
// 	Vertical: motorD
//	Horizontal: motorA

// Fwd - Forward; Bwd - Backward. Recta direction definitions
// Lft - Left; Rgt - Right. Turns direction definitions

// From max side to middle: 1.2
// From max up to down: 2.65
// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)

// ROBOPRO || VEATRIZ
//#define ROBOPRO

#include "Core/Core.h"

//#include "Sortida_2bR.h"
//#include "Sortida_2bR_Short.h"
//#include "Sortida_3R.h"
//#include "Sortida_4_Robopro.h"
void Align_S3()
{
	flushButtonMessages();
	MoveMotorTime(motorD, 2, 70);
	MoveMotorTime(motorA, 4, -30);
	MoveMotor(motorD, 2.65, -30);
}

void Sortida_3()
{
	flushButtonMessages();
	waitForButtonPress();
 	Recta(Fwd, 2.9, 40);
 	Recta(Bwd, 2.9, 70);

	//aliniat S3B NO BORRAR
	MoveMotor(motorD, 0.2, 30);
	MoveMotor(motorA, 1.1, -30);
}
