#pragma config(Sensor, S2,     ,               sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Motors:
//	Rigth: motorB
//	Left: motorC

// Wall:
// 	Vertical: motorD
//	Horizontal: motorA

// Fwd - Forward; Bwd - Backward. Recta direction definitions
// Lft - Left; Rgt - Right. Turns direction definitions

// From max side to middle: 1.2
// From max up to down: 2.65
// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)

// ROBOPRO || VEATRIZ
//#define ROBOPRO

#include "Core/Core.h"

//#include "Sortida_2bR.h"
//#include "Sortida_2bR_Short.h"
//#include "Sortida_3R.h"
//#include "Sortida_4_Robopro.h"
void Align_S4()
{
	flushButtonMessages();
	MoveMotorTime(motorD, 2, 70);
	MoveMotorTime(motorA, 4, -30);
	MoveMotor(motorD, 3, -50);
	MoveMotor(motorA, 1.7, 30);
}
void Sortida_4()
{
	//màxim esquerra 0.7 voltes a dalt
	//MoveMotorAsync(motorD, 0.7, 30);
	//MoveMotor(motorA, -1, 50);
	flushButtonMessages();
	waitForButtonPress();
	Recta(Fwd, 1.5, 40);
	FollowLine(2.5, 40, Rgt, Lft, true, false, 45, 0.9, 60, 0.1);  // primer tram
	FollowLine(2.5, 50, Rgt, Lft, false, false, 60, 0.9, 60, 0.1);  // segon tram
	WaitForLine(Fwd, 10, 20, Lft);   // Detectem banc
	Recta(Fwd, 0.5, 20, false, true); // ens posicionem per deixar helicopter
	//deixem peça
	MoveMotor(motorA, 1, 40);
	MoveMotor(motorD, 0.7, -40);
	MoveMotor(motorD, 0.02, 40);


	MoveMotor(motorA, 0.8, 40);
	//Cercle blau
	MoveMotor(motorD, 0.7, 40);
	//MoveMotor(motorA, 0.3, 40);
	//Turn(15, 20, Lft);
	FollowLine(0.5, 40, Rgt, Lft, true, false, 65,  0.8, 60, 0.1);
	MoveMotorAsync(motorD, 0.4, -40);
	FollowLine(1.8, 40, Rgt, Lft, false, true, 65,  0.8, 60, 0.1);
	MoveMotor(motorA, 1.5, -40);
	MoveMotor(motorD, 3, 40);
	resetGyro(S2);
	Recta(Bwd, 0.9, 50);
	Turn(-32, 20, Rgt);
	Recta(Bwd, 2.3, 50, true, false);
	WaitForLine(Bwd, 10, 20, Lft);   // Detectem banc
	Align(Bwd, 2);
	Recta(Fwd, 0.2, 20);
	resetGyro(S2);
	Turn(90, 20, Lft);
	MoveMotorTime(motorA, 2, 40);
	WaitForBlack(Fwd, 10, 20, Lft);   // Detectem banc
	Recta(Fwd, 0.52, 40);
	MoveMotor(motorD, -3, 40);
	MoveMotorTime(motorA, 2.5, -40);
	MoveMotor(motorD, 2, 40);
	resetGyro(S2);
	while(getColorReflected(S3) > 20){
		setMotorSpeed(motorB, -40);
		setMotorSpeed(motorC, -17);
	}
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
	Turn(90, 20, Lft);
	Recta(Bwd, 1.1, 40);
	//MoveMotor(motorD, -1, 40);
	MoveMotor(motorA, 1.1, 40);
	MoveMotor(motorD, -2.1, 40);
	//MoveMotorAsync(motorA, 0.2, 40);
	//MoveMotor(motorD, -1.1, 40);
	MoveMotorTime(motorA, 0.5, 20);

	Recta(Fwd, 0.55, 40);
	WaitForBlack(Fwd, 10, 20, Lft);   // Detectem banc
	MoveMotor(motorD, 0.8, 40);
}
