#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Wall:
// 	Vertical: motorD
//	Horizontal: motorA

// Fwd - Forward; Bwd - Backward. Recta direction definitions
// Lft - Left; Rgt - Right. Turns direction definitions

// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)

// ROBOPRO || VEATRIZ
#define ROBOPRO


#include "Core/Core.h";

task main()
{
	//Anem fins a M9 (Girar rodes)
	Recta(Fwd, 1.50, 80);

	//Girme M9
	MoveMotorAsync(motorA, 0.5, 50);
	Recta(Fwd, 0.15, 50);
	MoveMotorAsync(motorD, 0.25, 50); //mentres...
	Recta(Fwd, 0.20, 50);
	delay(100);

	//Coloquem
	MoveMotorAsync(motorD, -0.25, 30);
	Recta(Fwd, 0.20, 50);
	Recta(Bwd, 0.40, 80);	// aqui ja hem girat i collcat les rodes

	//Anem a fer la M(12)(posar la roda rara en el cercle)
	Recta(Fwd, 0.40, 50);
	Turn(Lft, 45, 50);
	MoveMotorAsync(motorD, 0.25, 50);
	Recta(Fwd, 0.10, 50);

	//Fem M12
	MoveMotorAsync(motorD, -0.25, 50);// aqui ja ens hem colocat i agafem la roda
	Turn(Lft, 45, 50); // la posem en el cercle
	MoveMotorAsync(motorD, 0.25, 50);
	Recta(Fwd, 0.10, 50);

	//Ens recoloquem
	Recta(Bwd, 0.60, 80); // aqui toca a la paret

	//Fem M14
	Recta(Fwd, 0.10, 50);
	Turn(Lft, 90, 50);	// va a agafar la M14 (aquella cosa petita que hi ha moltes i s'ha de penjar i dona punts)
	MoveMotorAsync(motorA, 0.25, 50);
	Recta (Fwd, 1.2, 50);

	//Tornem a la base
	MoveMotorAsync(motorD, 0.5, 50);
	MoveMotor(motorA, 0.5, 50);
	Recta (Fwd, 5.8, 50);
}
