#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// F - Forward; B - Backward. Recta direction definitions
// L - Left; R - Right. Turns direction definitions

// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)


#include "Core/Core.h";

task main()
{
	//Anem fins a la canasta
	Recta(Fwd, 0.75, 75);
	MoveMotorAsync(motorA, 0.975, 50);
	delay(500);
	Turn(Rgt, 60, 50);
	delay(10);
	Recta(Fwd, 2.3, 75);
	delay(10);
	Turn(Lft, 60, 50);
	delay(10);
	Recta(Fwd, 1.75, 75);
	delay(10);

	MoveMotor(motorA, 0.975, 100);

	Recta(Fwd, 01, 10);
}
