#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// F - Forward; B - Backward. Recta direction definitions
// L - Left; R - Right. Turns direction definitions

// From max side to middle: 1.1
// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)

#define VEATRIZ
#include "Core/Core.h";

task main()
{
	//Fem M??
	//Align
	MoveMotorTime(motorA, 3, -70)
	MoveMotorTime(motorD, 4, 70)
	MoveMotorTime(motorA, 0.7, 70)
	MoveMotor(motorD, -6.2, 50);
	resetGyro(S2);
	waitForButtonPress();


	//Fer ajust inicial
	//delay(250);
	//Recta(Bwd, 0.08, 20);
	//delay(250);

	//Fem M2
	Recta(Fwd, 6.4, 50);
	setMotorSpeed(motorB, 50);
	setMotorSpeed(motorC, 50);
	delay(200);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);

	//desenganchem
	Recta(Bwd, 0.8, 30);
	MoveMotor(motorA, 0.15, 70);
	MoveMotor(motorD, 0.1, 70);


	//gir
	Recta(Fwd, 0.9, 30);
	Recta(Bwd, 0.27, 30);
	Turn(Lft, 90, 50);

	//Ens col·loquem a la paret
	Recta(Bwd, 1, 50);
	resetGyro(S2);



	//Avançem fins a la M14
	MoveMotor(motorA, 0.8, 70);
	MoveMotorAsync(motorD, 3, 70);
	Recta(Fwd, 1.5, 50);


	//Fem la M14
	MoveMotor(motorD, 1, -30);
	Recta(Bwd, 0.4, 40);
	MoveMotor(motorA, 0.8, -50);
	MoveMotor(motorD, 2.25, -70);

	//Avançem fins a M8
	Recta(Fwd, 3, 50);
	Recta(Fwd, 0.5, 30);


	////Fem M8
	//Recta(Fwd, 1, 20);
	//Recta(Bwd, 1, 20);

	////Ens posicionem per M7
	//Turn(Lft, 45, 50);
	////Avançem fins M7

	//Recta(Fwd, 0.5, 50);

	////Fem bailecito
	//int n = 0;
	//while(n == 0) {
	//	Recta(Fwd, 0.2, 70);
	//	Recta(Bwd, 0.2, 70);
	//	Turn(Lft, 360, 60);
	//	Turn(Rgt, 360, 60);
	//}
}
