#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Wall:
// 	Vertical: motorD
//	Horizontal: motorA

// Fwd - Forward; Bwd - Backward. Recta direction definitions
// Lft - Left; Rgt - Right. Turns direction definitions

// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)

// ROBOPRO || VEATRIZ
#define VEATRIZ

#include "Core/Core.h";

task main()
{
	MoveMotorTime(motorA, 3, 70)
	MoveMotorTime(motorD, 4, 70)
	MoveMotor(motorD, -6.2, 50);

	resetGyro(S2);
	waitForButtonPress();

	//Fer ajust inicial
	delay(250);
	Recta(Bwd, 0.08, 20);
	delay(250);

//Anem fins a la canasta
	//Abancem fins catxarrito
	MoveMotor(motorA, -0.9, 50);
	Recta(Fwd, 1.5, 50);

	//Abancem fins humans
	Turn(Rgt, 60, 30);
	Recta(Fwd, 1.3, 50);

	//Arribem a canasta
	Turn(Lft, 58, 30);
	Recta(Fwd, 2.55, 50);

//Fem canasta
	//Deixem bloc
	setMotorBrakeMode(motorB, motorBrake);
	setMotorBrakeMode(motorC, motorBrake);
	MoveMotorTime(motorA, 2, 75);

	//Pujem primer pis
	MoveMotor(motorD, 3.5, 75);

	//Pujem segon pis
	MoveMotorTime(motorA, 3, -75);
	MoveMotor(motorD, -3.5, 75);
	Recta(Bwd, 0.1, 10)
	MoveMotorTime(motorA, 3.5, 75);
	Turn(Lft, 10, 25);
	Recta(Fwd, 0.2, 20);
	MoveMotor(motorD, 3, 75);
	Recta(Fwd, 0.1, 20);
	MoveMotor(motorD, 2.5, 75);

////Tornem base
	//Sortim canasta
	MoveMotorAsync(motorD, -5.5, 70);
	Recta(Bwd, 0.5, 50);
	MoveMotorAsync(motorA, 0.3, 70);

	//Agafem unitat de salut
	Turn(Lft, 55, 50);
	Recta(Fwd, 2.5, 75);
	Turn(Lft, 15, 50);
	Recta(Fwd, 1.5, 75);
}
