#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// F - Forward; B - Backward. Recta direction definitions
// L - Left; R - Right. Turns direction definitions

// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)
// Motor A --> horitzontal
// Motor B --> vertical

#define VEATRIZ

#include "Core/Core.h";

task main()
{
	setMotorBrakeMode(motorB, motorBrake);
	setMotorBrakeMode(motorC, motorBrake);

	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);

	waitForButtonPress();

	Recta(Fwd, 3, 70);
	MoveMotor(motorA, 1, 50);
	//Recta(Fwd, 2, 50);
	//Turn();

}
