#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// F - Forward; B - Backward. Recta direction definitions
// L - Left; R - Right. Turns direction definitions

// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)


#include "Core/Core.h";

task main()
{
	//Avançem fins a la petanca
	Recta(-1, 2, 25);

	//Girem per colocarnos i deixar tots els blocs
	Turn(1, 17, 20);

	MoveMotor(motorA, 1.2, 100);
	Recta(-1, 0.5, 75);
	Recta(1, 2.6, 100);
}
