#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// F - Forward; B - Backward. Recta direction definitions
// L - Left; R - Right. Turns direction definitions

// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)


#include "Core/Core.h";

task main()
{
	//Anem fins a la canasta
	Recta(-1, 0.75, 75);
		delay(100);
	Turn(1, 45, 20);
	Recta(-1, 2.3, 75);
	Turn(-1, 45, 20);
	Recta(-1, 1.5, 75);

	MoveMotor(motorA, 2, 100);
}
