#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// F - Forward; B - Backward. Recta direction definitions
// L - Left; R - Right. Turns direction definitions

// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)
// Motor A --> horitzontal
// Motor B --> vertical


#include "Core/Core.h";

task main()
{

	Recta(Fwd, 1.50, 80); //Anem fins a M9 (Girar rodes)
	MoveMotorAsync(motorA, 0.5, 50);
	Recta(Fwd, 0.15, 50)
	Recta(Fwd, 0.15, 50); //metres...
	MoveMotorAsync(motorB, 0.25, 50);
	Recta(Fwd, 0.20, 50);
	Recta(Bwd, 0.40, 80);	// aqui ja hem girat i collcat les rodes
	MoveMotorAsync(motorB, -0.10, 50); //anem a fer la M(??)(posar la roda rara en el cercle)
	Recta(Fwd, 0.10, 50);
	Turn(Rgt, 45, 50);
	Recta(Fwd, 0.10, 50);
	MoveMotorAsync(motorB, 0.25, 50);
	MoveMotorAsync(motorB, -0.30, 50);// aqui ja ens hem colocat i agafem la roda
	Turn(Rgt, 40, 50); // la posem en el cercle
	Recta(Fwd, 0.10, 50);
	MoveMotorAsync(motorB, 0.5, 50);
	Recta(Bwd, 0.60, 80); // aqui toca a la paret
	Recta(Fwd, 0.10, 50);
	Turn(Rgt, 40, 50);	// va a agafar la M14 (aquella cosa petita que hi ha moltes i s'ha de penjar i dona punts)


			delay(500);
			Turn(Rgt, 60, 50);
			delay(10);
			Recta(Fwd, 2.3, 75);
			delay(10);
			Turn(Lft, 60, 50);
			delay(10);
			Recta(Fwd, 1.75, 75);
			delay(10);


	MoveMotor(motorA, 0.975, 100);

	Recta(Fwd, 01, 10);
}
