#pragma config(Sensor, S2,     ,               sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Motors:
//	Rigth: motorB
//	Left: motorC

// Wall:
// 	Vertical: motorD
//	Horizontal: motorA

// Fwd - Forward; Bwd - Backward. Recta direction definitions
// Lft - Left; Rgt - Right. Turns direction definitions

// From max side to middle: 1.2
// From max up to down: 2.65
// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)

// ROBOPRO || VEATRIZ
//#define ROBOPRO

#include "Core/Core.h"

//#include "Sortida_2bR.h"
//#include "Sortida_2bR_Short.h"
//#include "Sortida_3R.h"
//#include "Sortida_4_Robopro.h"
void Align_S2()
{
	flushButtonMessages();
	MoveMotorTime(motorD, 5, 30);
	MoveMotorTime(motorA, 4, 20);
	//MoveMotor(motorA, 1.5, 50);
	MoveMotor(motorD, 0.9, -50); //0.7


}
void Sortida_2()
{
	//fase 1: anada
	waitForButtonPress();
	resetGyro(S2);
	flushButtonMessages();
	delay(200);

	//sortida
	Recta(Fwd, 1.5, 40, false, false, 1, 0.85);
	WaitForBlack(Fwd, 10, 30, Rgt, false);
	delay(100);
	WaitForLine(Fwd, 10, 30, Rgt, false);

	//Tram 1: Gir
	FollowLine(1.5, 40, Rgt, Lft, false, false, 45, 0.9, 60, 0.1);  // primer tram //1

	//Tram 2:
	FollowLine(1.5, 50, Rgt, Lft, false, false, 45, 0.4, 40, 0.09); //1

	//Tram 3: Arribem pon
	FollowLine(0, 50, Rgt, Lft, false, false, 45, 0.4, 40, 0.09);
	FollowLine(0.8, 50, Rgt, Lft, false, false, 45, 0.4, 40, 0.09);
	FollowLine(0, 50, Rgt, Lft, false, false, 45, 0.4, 40, 0.09);
	Recta(Fwd, 0.5, 30, false, true);

	//Coloquem Wall
	MoveMotorAsync(motorD, 1, -70);
	MoveMotor(motorA, 2, -70);
	MoveMotorTime(motorA, 0.3, -70);

	//Fem Grua
	Recta(Fwd, 0.6, 60, true, false, 0.75);
	setMotorSpeed(motorB, -50);
	setMotorSpeed(motorC, -50);
	delay(300);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);

	//Sortim Grua
	MoveMotorAsync(motorA, 1, 80);
	MoveMotor(motorD, 1.7, 80);
	WaitForBlack(Fwd, 10, 30, Lft, false);
	delay(100);
	WaitForLine(Fwd, 10, 30, Lft);

	//Anem helicopter
	while(getColorReflected(S4)>=30){
	setMotorSpeed(motorB, -15);
	setMotorSpeed(motorC, 10);
	}
	FollowLine(1.7, 40, Lft, Rgt, false, false, 35, 0.9, 60, 0.1);
	WaitForLine(Fwd, 10, 20, Rgt);

	//Arribem helicopter
	MoveMotorAsync(motorA, 0.8, 70);
	Turn(-137, 20, Rgt);
	MoveMotorAsync(motorD, 1.7, -70);//1.3
	Recta(Bwd, 2.3, 70, false, false);//1 //2.5
	resetGyro(S2);

	//Tirem paquet helicopter
	MoveMotor(motorA, 1.5, -80);
	MoveMotorTime(motorA, 0.3, -70);

	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);

	MoveMotor(motorA, 1.8, 80);
	//MoveMotorTime(motorA, 0.3, 70);
	//MoveMotorAsync(motorD, 1.3, -40);

	//Fem tren
	//Avancem fins balnca
	//MoveMotor(motorA, 1.5, 80); //2, 1.7// 1.5
	MoveMotorAsync(motorD, 1.2, -40);//0.8
	WaitForLine(Fwd, 10, 30, Rgt, false);
	////Fem tren tirar via
	Recta(Fwd, 0.4, 30, false, false);
	//nem lent perl tren
	Recta(Fwd, 0.6, 10, false, false);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
	Turn(0, 30, Rgt);

	//després d'anar lent anem a per les peçes i assegurem cap  a baix
	MoveMotorAsync(motorD, 0.05, -20);
	//avançem ràpid per si de cas
	Recta(Fwd, 1, 30, false, false);//1 //2.5 //false, true
	//MoveMotorTime(motorD, 0.5, -1);
	Recta(Fwd, 0.85, 30, false, false);//1 //2.5 //0.7
	setMotorSpeed(motorB, -30);
	setMotorSpeed(motorC, -30);
	delay(500);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);

		//Tornem
	MoveMotor(motorD, 0.5, 80);
	MoveMotorAsync(motorA, 0.5, -80);
	MoveMotor(motorD, 2, 70);
	Recta(Bwd, 1.5, 50, false, true);//1.8

	//Agafem linea negre
	Turn(-90, 20, Rgt);
	WaitForBlack(Fwd, 10, 40, Lft, false);   // Detectem negre
	Recta(Fwd, 0.3, 20, false, false);
		while(getColorReflected(S4)<=75){//85
		setMotorSpeed(motorC, 30);
		setMotorSpeed(motorB, -30);
		}
		setMotorSpeed(motorB, 0);
		setMotorSpeed(motorC, 0);
		delay(10);

		while(getColorReflected(S4)>=45){
		setMotorSpeed(motorC, 30);
		setMotorSpeed(motorB, -40);
		}
		setMotorSpeed(motorB, 0);
		setMotorSpeed(motorC, 0);
		delay(10);

		while(getColorReflected(S4)<=20){
		setMotorSpeed(motorC, -20);
		setMotorSpeed(motorB, 20);
		}
		setMotorSpeed(motorB, 0);
		setMotorSpeed(motorC, 0);
		delay(10);

	FollowLine(0.4, 45, Lft, Rgt, false, false, 0, 0.9, 60, 0.1);  // primer tram

		while(getColorReflected(S4)>=55){
		setMotorSpeed(motorC, 20);
		setMotorSpeed(motorB, -20);
		}

	FollowLine(0.5, 60, Lft, Rgt, false, false, 50, 0.9, 60, 0.1);  // primer tram

	//Gir chungo pon
	WaitForBlack2(Fwd, 10, 30, Rgt, 1, 0.6, false);//0.7   // Detectem negre
	WaitForLine2(Fwd, 10, 20, Lft, 1, 0.6, false);   // Detectem blanc
	Recta(Fwd, 0.1, 20, false, false, 0.75);

		while(getColorReflected(S4)>=20){
		setMotorSpeed(motorC, -30);
		setMotorSpeed(motorB, 30);
		}
		delay(40);
		setMotorSpeed(motorC, 0);
		setMotorSpeed(motorB, 0);

	//Acavem de tornar
	FollowLine(1.8, 60, Lft, Rgt, false, false, 35, 0.9, 60, 0.1);
	//MoveMotorAsync(motorD, 0.3, -50);
	Recta(Fwd, 1.5, 75, false, false, 1, 0.9);
	Recta(Fwd, 4.5, 75, false, false);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
	delay(4000);
	MoveMotor(motorD, 0.7, 50);
	MoveMotor(motorD, 3, -50);
}
