#pragma config(Sensor, S2,     ,               sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Motors:
//	Rigth: motorB
//	Left: motorC

// Wall:
// 	Vertical: motorD
//	Horizontal: motorA

// Fwd - Forward; Bwd - Backward. Recta direction definitions
// Lft - Left; Rgt - Right. Turns direction definitions

// From max side to middle: 1.2
// From max up to down: 2.65
// Recta(Direction, Count, Power)
// Turn(Direction, Angle, Power)
// Align(Direction, Time)
// MoveMotor(Motor, Count, Power)
// MoveMotorAsync(Motor, Count, Power)

// ROBOPRO || VEATRIZ
//#define ROBOPRO
#define VEATRIZ

#include "Core/Core.h"

//#include "Sortida_2bR.h"
//#include "Sortida_2bR_Short.h"
//#include "Sortida_3R.h"
//#include "Sortida_4_Robopro.h"

task main()
{
	//fase 1: anada
	//Align wall(no acabat)
	MoveMotorTime(motorA, 4, -20);
	MoveMotorTime(motorD, 5, 30);
	MoveMotor(motorA, 1.3, 50);  //abans 0.8
	MoveMotor(motorD, 0.8, -50);

	////avançar fins línia(no fet)
	////avançar fins prova
	waitForButtonPress();
	Recta(Fwd, 1.5, 40, true, true, 1, 0.8);
	WaitForBlack(Fwd, 10, 30, Rgt);
	WaitForLine(Fwd, 10, 30, Rgt);
	MoveMotorAsync(motorD, 0.7, -50);
	FollowLine(1, 40, Rgt, Lft, true, false, 45, 0.9, 60, 0.1);  // primer tram
	FollowLine(3, 50, Rgt, Lft, false, false, 60, 0.6, 60, 0.1);  // segon tram//2.5

	MoveMotorAsync(motorD, 0.4, 50);
	WaitForLine(Fwd, 10, 20, Lft);   // Detectem banc
	resetGyro(S2);
	Recta(Fwd, 0.4, 30, false, true); //Avançar per tirar pont //0.5

	//tirar pont
	//MoveMotor(motorD, 1.5, -60);//1
	//MoveMotor(motorA, 0.3, -50);

// deixar peça i moure grua
	MoveMotorAsync(motorD, 2.7, -70);//1
	Recta(Fwd, 0.7, 40, false, false); //0.7
	Turn(0, 60, Rgt);
	MoveMotor(motorA, 0.7, -50);
//fase 2
	MoveMotor(motorD, 2.8, 60);
	MoveMotor(motorA, 1.3, 70);//1.4


	Recta(Fwd, 0.55, 30);
	while(getColorReflected(S4)>=30){
	setMotorSpeed(motorB, -15);
	setMotorSpeed(motorC, 10);
	}

	FollowLine(1.7, 40, Lft, Rgt, false, false, 35, 0.9, 60, 0.1);
	WaitForLine(Fwd, 10, 20, Rgt);
	//Recta(Fwd, 0.1, 50, false, false);//1
	Turn(-90, 30, Rgt);

	Recta(Bwd, 2.5, 70, false, false);//1
	resetGyro(S2);

	MoveMotor(motorD, 1.8, -60);
	MoveMotorTime(motorA, 1.5, -60);
	//MoveMotor(motorD, 1, 60);

	//fase 3
	MoveMotor(motorA, 1.1, 60);


	MoveMotorAsync(motorD, 0.9, -40);
	resetMotorEncoder(motorC);
	resetMotorEncoder(motorB);
	WaitForLine(Fwd, 10, 30, Rgt);
	float count;
	float count1;
	float motormov;
	count = getMotorEncoder(motorC);
	count1 = count  + 395;
	count1 = count1/-10;
	motormov = count1 * 0.13;
	MoveMotor(motorA, -motormov, 30);//MoveMotor(30)
	count = getMotorEncoder(motorC)/360;
	float mov;
	mov = 1.5 + count;
	Recta(Fwd, mov, 40, false, false, 0.98);
	Recta(Fwd, 0.4, 10, false, false, 0.98, 1);
	MoveMotor(motorA, -1 -motormov, 30);//MoveMotor(30)
	Recta(Fwd, 1.7, 30, false, false, 0.98, 1);
	setMotorSpeed(motorB, -40);
	setMotorSpeed(motorC, -70);
	delay(400);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
	MoveMotor(motorD, 1, 50);
	setMotorSpeed(motorB, -50);
	setMotorSpeed(motorC, -50);
	delay(400);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);

//Tornem
	MoveMotorTime(motorD, 2, 70);//2
	MoveMotorTime(motorA, 2, -50);//2
	Recta(Bwd, 1.95, 50);//1.5 //2
	Turn(-90,40,Rgt);
	WaitForBlack(Fwd, 10, 40, Lft);   // Detectem negre
	MoveMotorAsync(motorD, 0.2, 70);
	Recta(Fwd, 0.3, 20, false, false);

		while(getColorReflected(S4)<=85){
		setMotorSpeed(motorC, 30);
		setMotorSpeed(motorB, -30);
		}
		setMotorSpeed(motorB, 0);
		setMotorSpeed(motorC, 0);
		delay(5000);

		while(getColorReflected(S4)>=45){
		setMotorSpeed(motorC, 30);
		setMotorSpeed(motorB, -40);
		}
		setMotorSpeed(motorB, 0);
		setMotorSpeed(motorC, 0);
		delay(5000);


		while(getColorReflected(S4)<=25){
		setMotorSpeed(motorC, -20);
		setMotorSpeed(motorB, 20);
		}
		setMotorSpeed(motorB, 0);
		setMotorSpeed(motorC, 0);
		delay(5000);


	MoveMotorAsync(motorD, 0.3, 70);//2
	FollowLine(0.4, 45, Lft, Rgt, false, false, 0, 0.9, 60, 0.1);  // primer tram

		while(getColorReflected(S4)>=55){
		setMotorSpeed(motorC, 20);
		setMotorSpeed(motorB, -20);
		}

	FollowLine(0.5, 60, Lft, Rgt, false, false, 0, 0.9, 60, 0.1);  // primer tram

	WaitForBlack2(Fwd, 10, 30, Rgt, 0.7);   // Detectem negre
	WaitForLine2(Fwd, 10, 20, Lft, 0.7);   // Detectem blanc
	Recta(Fwd, 0.1, 20, false, false, 0.75);

	setMotorSpeed(motorC, 0);
	setMotorSpeed(motorB, 0);

		while(getColorReflected(S4)>=20){
		setMotorSpeed(motorC, -30);
		setMotorSpeed(motorB, 30);
		}
		delay(40);
		setMotorSpeed(motorC, 0);
		setMotorSpeed(motorB, 0);

	MoveMotorAsync(motorA, 1.7, 40);
	FollowLine(1.8, 60, Lft, Rgt, false, false, 35, 0.9, 60, 0.1);
	Recta(Fwd, 2, 75, false, false, 1, 0.85);
	MoveMotorAsync(motorD, 3, -50);
	Recta(Fwd, 4, 75, false, false);
}
